### ISSUE TITLE
indentation 'typos' in yaml files and replacing P(X) with number

### ISSUE THREAD

**Issue by vnijs** [gluc/data.tree#31]
As my students start to use Radiant and the data.tree based module I realized that the error messages produced by yaml and the dtree function in Radiant are not very informative, even for seemingly minor typos. I added a function to check for (some) indentation problems in yaml files (see [here](https://github.com/vnijs/radiant/blob/master/R/dtree.R#L1-L88)). Comments welcome.

As I wrote this up I realize I could also use `gsub` to replace variables defined in a yaml input file with values. To illustrate the idea see the input file below. This seems to work pretty well but I'm curious if you have a better alternative.

I think something like this could also be used to 'replace' chunks of a tree that are repeated several times. It might be easier, however, to just evaluate that chunk separately and use something like the `gsub` approach to plug in the expect value for the sub-tree. Comments?

```yaml
P(SBO) = .3
P(MBO) = (1 - P(SBO))/2
P(LBO) = (1 - P(SBO))/2
name: Jenny Lind
type: decision
Sign with Movie Company:
    type: chance
    Small Box Office:
        p: P(SBO)
        payoff: 200000
    Medium Box Office:
        p: P(MBO)
        payoff: 1000000
    Large Box Office:
        p: P(LBO)
        payoff: 3000000
Sign with TV Network:
    type: chance
    Small Box Office:
        p: P(SBO)
        payoff: 900000
    Medium Box Office:
        p: P(MBO)
        payoff: 900000
    Large Box Office:
        p: P(LBO)
        payoff: 900000
```

**Comment by vnijs** [comment]
Or maybe something like the yaml file below. This could be evaluated before it is processed by data.tree. Ideas/comments?

```yaml
variables: p_small = .1; p_medium = (1 - p_small)/2; p_large = (1 - p_small)/2
name: Jenny Lind
type: decision
Sign with Movie Company:
  type: chance
  Small Box Office:
    p: p_small
    payoff: 200000
  Medium Box Office:
    p: p_medium
    payoff: 1000000
  Large Box Office:
    p: p_large
    payoff: 3000000
Sign with TV Network:
  type: chance
  Small Box Office:
    p: p_small
    payoff: 900000
  Medium Box Office:
    p: p_medium
    payoff: 900000
  Large Box Office:
    p: p_large
    payoff: 900000
```
