### ISSUE TITLE
Cannot convert YAML to data.tree

### ISSUE THREAD

**Issue by gluc** [gluc/data.tree#58]
In a nutshell, the YAML I'm trying to import with `FromListExplicit` is:

```
children:
  CR:
    description: Currencies
    type: Currency
    children:
      CR_CHF: market
      CR_EUR: market
      CR_USD: market
```

I also tried:

```
children:
  CR:
    description: Currencies
    type: Currency
    children:
      - CR_CHF
      - CR_EUR
      - CR_USD
```
